site_name: DL4J SameDiff computation graph engine
theme: readthedocs
docs_dir: doc_sources
repo_url: https://github.com/deeplearning4j/deeplearning4j
site_url: http://deeplearning4j.org
site_description: 'DL4J SameDiff computation graph engine'

dev_addr: '0.0.0.0:8000'

pages:
- Home: index.md
- Getting started:
  - Building and running SameDiff graphs: getting-started/building-graphs.md
  - TensorFlow and ONNX import: getting-started/model-import.md
  - SameDiff and DL4J: getting-started/samediff-dl4j.md
- SameDiff graphs:
  - SameDiff variables: samediff/variables.md
  - SameDiff graphs and operations: samediff/samediff.md
  - SameDiff execution: samediff/execution.md
- Samediff functions:
  - Differential functions: functions/function-factory.md
- Adding new SameDiff ops: adding-ops.md